### PR TITLE
Minor proposed docstring revisions

### PR DESCRIPTION
**Pull request by ThomasA**
This pull request is part of the review in https://github.com/openjournals/joss-reviews/issues/749

### CODE REVIEW

**Comment by astorfi** [comment]
Please update you fork once again. As I made a lot of changes comparing the fork that you have.

**Comment by ThomasA** [comment]
OK, I rebased the commits and made a few more edits. How about now?

**Comment by astorfi** [comment]
You commit has conflict. Please remove this pull request, update your fork and commit again.

**Comment by ThomasA** [comment]
I rebased the feature branch - hope it is OK now?

**Comment by astorfi** [comment]
Thank you so much for your modifications.

**Pull request merged**
